-- Fix User Foreign Key to point to PUBLIC.users instead of AUTH.users
-- This is required because Supabase JS client joins usually work on public schema tables

-- 1. Drop existing FK constraint (name might vary, so we try standard autogenerated name)
ALTER TABLE public.qr_codes
DROP CONSTRAINT IF EXISTS qr_codes_assigned_user_id_fkey;

-- 2. Add new FK constraint validation public.users
ALTER TABLE public.qr_codes
ADD CONSTRAINT qr_codes_assigned_user_id_fkey
FOREIGN KEY (assigned_user_id)
REFERENCES public.users(id)
ON DELETE SET NULL;

-- 3. Also fix generated_by if needed (optional but good for consistency)
ALTER TABLE public.qr_codes
DROP CONSTRAINT IF EXISTS qr_codes_generated_by_fkey;

ALTER TABLE public.qr_codes
ADD CONSTRAINT qr_codes_generated_by_fkey
FOREIGN KEY (generated_by)
REFERENCES public.users(id)
ON DELETE SET NULL;
